### ISSUE TITLE
In Qualys connector, `get_bearer_token` crashes import

### ISSUE THREAD

**Issue by barvhaim** [IBM/cp4s-car-connectors#77] opened 2023-01-11 19:22 UTC
Unless in comment out the `get_applications` part that uses `get_bearer_token`, the connector is crashed with error: 
```
connectors/qualys/connector/server_access.py\", line 197, in get_bearer_token\n    response_json = response.json()\n  File \"/Users/barha/.pyenv/versions/3.9.13/lib/python3.9/site-packages/requests/models.py\", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "connector": "Qualys", "source": "qq2"}

Process finished with exit code 1
```

**Comment by thummalar** [comment] 2023-01-12 14:07
As per our initial analysis, 'JSONDecodeError' would come when we get an empty response while trying to get bearer token.
Kindly let us know on the following for further analysis.
1.	Is connector crashing for every import consistently or randomly?
2.	Assuming connector crashing in incremental import, how frequently incremental imports are running?

**Comment by thummalar** [comment] 2023-02-28 07:05
As confirmed in slack channel on 21-Feb-2023, the issue is addressed after passing the correct Qualys Gateway URL.
Hence request to close the issue.

**Closed as completed** 2023-04-05 13:40 UTC
